POST http://localhost:3003/api/topics
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImEiLCJpZCI6IjY1M2M4MzRmNGUzMjM5YjYzZWM0ODNkZSIsImlhdCI6MTY5ODUwMTgyMCwiZXhwIjoxNjk4NTA1NDIwfQ.Dd3U18_B1oqBwBfbL8XLwzDc9mLoys98DDMBEyaMTSk

{
  "title": "title"
}